site_name: ICMOD WIKI
repo_url: https://github.com/McdheYxY/icmod-wiki
site_url: https://wiki.icmod.tech
use_directory_urls: false
theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: amber
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features: 
    #提前加载
    - navigation.instant
    - navigation.tabs
    #进度显示
    - navigation.instant.progress
  language: zh
nav:
  - 教程: 
    - Guide: 
      - Guide/介绍.md
      - Guide/初步.md
    - Blocks: 
      - Blocks/介绍.md
      - Blocks/初步.md
    - Items: 
      - Items/介绍.md
      - Items/初步.md
    - UI: 
      - UI/介绍.md
      - UI/初步.md
  - 介绍:
    - horizon由来: horizon_origin.md
    - horizon详细: horizon_more.md
    - 作者: author.md
  - more.md
extra_css:
  - assets/css/style.css
markdown_extensions:
  - toc:
      permalink: "#"
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  alternate:
    - name: 中文
      link: /
      lang: zh
    - name: Einglish
      link: /en/
      lang: en
